#!/usr/bin/env ruby
links = [
  '~/Development/projects/vim/vim-deliminator',
  '~/Development/projects/vim/vim-layout'
  # '~/Development/projects/vim/vim-toggle-block',
  '~/Development/projects/vim/vim-todo'
  '~/Development/projects/vim/vim-tree'
]

git_bundles = [
  "git://github.com/godlygeek/csapprox.git",
  "git://github.com/mileszs/ack.vim.git"
  "git://github.com/kien/ctrlp.vim.git"
  "git://github.com/msanders/snipmate.vim.git",

  "git://github.com/tpope/vim-endwise.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tsaleh/vim-tcomment.git",

  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/vim-scripts/vim-coffee-script.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-cucumber.git",

  # "git://github.com/bronson/vim-scrollcolors.git",
  # "git://github.com/astashov/vim-ruby-debugger.git",
  # "git://github.com/tpope/vim-rails.git",
  # "git://github.com/tpope/vim-git.git",
  # "git://github.com/tpope/vim-fugitive.git",
  # "git://github.com/tpope/vim-repeat.git",
  # "http://github.com/tpope/vim-unimpaired.git",
  # "http://github.com/tsaleh/vim-supertab.git",
  # "git://github.com/tsaleh/vim-align.git",
  # "http://github.com/scrooloose/syntastic.git",
  # "http://github.com/tpope/vim-abolish.git",
  # "http://github.com/vim-scripts/YankRing.vim"
]

require 'fileutils'
require 'open-uri'

dir = File.expand_path('../bundle', __FILE__)

puts "Trashing bundle/"
FileUtils.rm_rf(dir)
FileUtils.mkdir(dir)
FileUtils.cd(dir)

links.each do |path|
  File.symlink(File.expand_path(path), File.basename(path))
end

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end
